version: '2'
services:
  myapp:
    image: docker.io/bitnami/codeigniter:3
    ports:
      - '8000:8000'
    volumes:
      - './Projet_PHP:/app'
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
       - "./Projet_PHP/stages_projet.sql:/docker-entrypoint-initdb.d/1.sql" #script initial lancé pour créer la base de donnée et mettre les données de test